
site_name: Planung
site_description: Wiki-Artige Dokumentensammlung zur projektorganisation

nav:
- 'index.md'
#- 'Vision.md'
- 'Ausgangslage.md'
- 'Ziele.md'
- 'Fragestellungen.md'
#- 'Organisation.md'
#- 'Möglichkeiten.md'
#- 'Finanzen.md'