name: Convert Markdown to HTML

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install pandoc

    - name: Convert Markdown to HTML
      run: |
        mkdir output
        pandoc -s -o output/Readme.html README.md

    - name: Move HTML files to specific folder
      run: |
        mkdir -p out
        mv output/*.html out
        
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Your Name
        author_email: daniel.zbinden@dzb-projects.ch
        message: 'Convert Markdown files to HTML'
